apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-config
  namespace: default
data:
  APP_NAME: "Voyages Scolaires"
  APP_ENV: production
  APP_DEBUG: "false"
  APP_URL: http://localhost:8080
  [cite_start]LOG_CHANNEL: stderr # [cite: 133] Les logs vont vers la sortie standard pour être lus par 'kubectl logs' [cite: 134]
  
  # Configuration de la base de données (cible le futur service de Jonathan) [cite: 133]
  DB_CONNECTION: mysql
  [cite_start]DB_HOST: mariadb # Nom du Service MariaDB que ton binôme va créer [cite: 133]
  [cite_start]DB_PORT: "3306" [cite: 133]
  [cite_start]DB_DATABASE: voyages_scolaires [cite: 133]
  
  # RÉSOLUTION DE LA PANNE STATELESS 
  [cite_start]SESSION_DRIVER: database # On force les sessions en BDD [cite: 176]
  CACHE_STORE: database