apiVersion: v1
kind: Secret
metadata:
  name: laravel-secrets
type: Opaque
stringData:
  APP_KEY: "base64:exiPVbjHRngeYGZ/y4IH6Sxqo5Z+rYotabV2g0GIkX8="
  DB_USERNAME: "laravel"
  DB_PASSWORD: "password"
  DB_ROOT_PASSWORD: "rootpassword"