apiVersion: v1
kind: Secret
metadata:
  name: laravel-secrets
  namespace: default
type: Opaque
stringData:
  APP_KEY: "" # À générer localement
  DB_USERNAME: ""
  DB_PASSWORD: ""
  [cite_start]DB_ROOT_PASSWORD: "" #  Requis pour l'initialisation de MariaDB par ton binôme